server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  ratelimiter:
    instances:
      priceLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0
  circuitbreaker:
    instances:
      riskBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 1
